/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.MyUtil;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.Clock;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import oracle.net.aso.l;

/**
 *
 * @author ABDOU
 */
public class sup_contrat extends javax.swing.JInternalFrame {

    Connection conn = MyUtil.seConnecter();
    ResultSet rs;
    ResultSet rsr;
    DefaultTableModel df ;
    
    /**
     * Creates new form sup_contrat
     */
    public sup_contrat() throws Exception {
        initComponents();
        df = (DefaultTableModel) jTable1.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("suprimer contrat");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("rechercher");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "CODE CLIENT", "NOM", "ETAT", "TYPE", "P N", "P O", "DATE ", "TECH", "no_contrat"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setText("supprimer");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("Modifier");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jCheckBox1.setText("mofier client");

        jCheckBox2.setText("modifier contrart");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("CLIENT :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCheckBox1)
                                .addGap(30, 30, 30)
                                .addComponent(jCheckBox2)
                                .addGap(75, 75, 75)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(380, 380, 380)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox2))
                .addGap(0, 39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            df.setRowCount(0);
            String req = "select * from contrat where lower(nom) like'%"+jTextField1.getText()+"%' or upper(nom) like'%"+jTextField1.getText()+"%'";
                jTextField1.setText("");
                rs=conn.createStatement().executeQuery(req);
            SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
            
             while(rs.next()){
                df.addRow(new Object[]{rs.getString(8),rs.getString(9),rs.getString(2),rs.getString(3),
                    rs.getInt(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(1)});
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(sup_contrat.class.getName()).log(Level.SEVERE, null, ex);
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int row= jTable1.getSelectedRow();
        if(jTable1.getSelectedRowCount()==1){
            try {
                conn.createStatement().executeUpdate("delete from contrat where no_contrat='"+df.getValueAt(row ,11)+"'");
                conn.commit();
                df.removeRow(jTable1.getSelectedRow());
            } catch (SQLException ex) {
                Logger.getLogger(recherech_sup_mod.class.getName()).log(Level.SEVERE, null, ex);
            }
        }     
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        try {
            // TODO add your handling code here:
            conn.close();
            System.out.println("deconecter");
        } catch (SQLException ex) {
            Logger.getLogger(sup_contrat.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formInternalFrameClosed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            int row =jTable1.getSelectedRow();
            if(jCheckBox1.isSelected()){
                String adress = df.getValueAt(row, 2).toString();
                String syndic = df.getValueAt(row, 3).toString();
                String app = df.getValueAt(row, 4).toString();
                
                String Newadress = JOptionPane.showInputDialog(null,"Enter The New adress",adress);
                String Newsyndic = JOptionPane.showInputDialog(null,"Enter The New Idsydic",syndic);
                String Newapp = JOptionPane.showInputDialog(null,"Enter The New app",app);
                
                df.setValueAt(Newadress,row, 2);
                conn.createStatement().executeUpdate("update client set adress='"+Newadress+"' where code_clt='"+df.getValueAt(row,0)+"'");
                df.setValueAt(Newsyndic,row, 3);
                conn.createStatement().executeUpdate("update client set syndic='"+Newsyndic+"' where code_clt='"+df.getValueAt(row,0)+"'");
                df.setValueAt(Newapp,row, 4);
                conn.createStatement().executeUpdate("update client set app='"+Newapp+"' where code_clt='"+df.getValueAt(row,0)+"'");
            }
            if(jCheckBox2.isSelected()){
               String type = df.getValueAt(row, 6).toString();
               String tech = df.getValueAt(row, 10).toString();
           
               String Newtype = JOptionPane.showInputDialog(null,"Enter The New type",type);
               String Newtech = JOptionPane.showInputDialog(null,"Enter The New tech",tech); 
               
                if(df.getValueAt(row,5).equals("N")){
            String pn = df.getValueAt(row, 7).toString(); 
            String Newpn = JOptionPane.showInputDialog(null,"Enter The New P N",pn);
            df.setValueAt(Newpn,row, 7);
            conn.createStatement().executeUpdate("update contrat set P_N='"+Newpn+"' where no_contrat='"+df.getValueAt(row,0)+"'");
            }else if (df.getValueAt(row,5).equals("O")){
            String po = df.getValueAt(row, 8).toString();
            String Newpo = JOptionPane.showInputDialog(null,"Enter The New P O",po);
            df.setValueAt(Newpo,row, 8);
            conn.createStatement().executeUpdate("update contrat set P_O='"+Newpo+"' where no_contrat='"+df.getValueAt(row,0)+"'");
            }
            df.setValueAt(Newtype,row, 9);
            conn.createStatement().executeUpdate("update contrat set type_contrat='"+Newtype+"' where no_contrat='"+df.getValueAt(row,0)+"'");
            df.setValueAt(Newtech,row, 10);
            conn.createStatement().executeUpdate("update contrat set tech='"+Newtech+"' where no_contrat='"+df.getValueAt(row,0)+"'");
            }
            conn.commit();
        } catch (SQLException ex) {
            Logger.getLogger(sup_contrat.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        jCheckBox1.setVisible(true);
        jCheckBox2.setVisible(true);
    }//GEN-LAST:event_jTable1MouseClicked

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        jCheckBox1.setVisible(false);
        jCheckBox2.setVisible(false);
    }//GEN-LAST:event_formInternalFrameOpened

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
