package gnots.models;
// Generated 9 f�vr. 2021 09:45:32 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Etudiant generated by hbm2java
 */
@Entity
@Table(name="ETUDIANT"
    ,schema="GNOTES"
)
@SequenceGenerator(name = "seq_e", sequenceName = "seq_etu")
public class Etudiant  implements java.io.Serializable {


     private long idE;
     private Groupe groupe;
     private String nom;
     private String prenom;
     private Set<Notes> noteses = new HashSet<Notes>(0);

    public Etudiant() {
    }

	
    public Etudiant(long idE) {
        this.idE = idE;
    }
    public Etudiant(long idE, Groupe groupe, String nom, String prenom, Set<Notes> noteses) {
       this.idE = idE;
       this.groupe = groupe;
       this.nom = nom;
       this.prenom = prenom;
       this.noteses = noteses;
    }
   
     @Id 

    @GeneratedValue(generator = "seq_e",strategy = GenerationType.SEQUENCE)
    @Column(name="ID_E", unique=true, nullable=false, precision=10, scale=0)
    public long getIdE() {
        return this.idE;
    }
    
    public void setIdE(long idE) {
        this.idE = idE;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_G")
    public Groupe getGroupe() {
        return this.groupe;
    }
    
    public void setGroupe(Groupe groupe) {
        this.groupe = groupe;
    }

    
    @Column(name="NOM", length=25)
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }

    
    @Column(name="PRENOM", length=30)
    public String getPrenom() {
        return this.prenom;
    }
    
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="etudiant")
    public Set<Notes> getNoteses() {
        return this.noteses;
    }
    
    public void setNoteses(Set<Notes> noteses) {
        this.noteses = noteses;
    }




}


