package gnots.models;
// Generated 9 f�vr. 2021 09:45:32 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Groupe generated by hbm2java
 */
@Entity
@Table(name="GROUPE"
    ,schema="GNOTES"
)
public class Groupe  implements java.io.Serializable {


     private long idG;
     private String libele;
     private Set<Etudiant> etudiants = new HashSet<Etudiant>(0);
     private Set<Examen> examens = new HashSet<Examen>(0);

    public Groupe() {
    }

	
    public Groupe(long idG) {
        this.idG = idG;
    }
    public Groupe(long idG, String libele, Set<Etudiant> etudiants, Set<Examen> examens) {
       this.idG = idG;
       this.libele = libele;
       this.etudiants = etudiants;
       this.examens = examens;
    }
   
     @Id 

    
    @Column(name="ID_G", unique=true, nullable=false, precision=10, scale=0)
    public long getIdG() {
        return this.idG;
    }
    
    public void setIdG(long idG) {
        this.idG = idG;
    }

    
    @Column(name="LIBELE", length=25)
    public String getLibele() {
        return this.libele;
    }
    
    public void setLibele(String libele) {
        this.libele = libele;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="groupe")
    public Set<Etudiant> getEtudiants() {
        return this.etudiants;
    }
    
    public void setEtudiants(Set<Etudiant> etudiants) {
        this.etudiants = etudiants;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="groupe")
    public Set<Examen> getExamens() {
        return this.examens;
    }
    
    public void setExamens(Set<Examen> examens) {
        this.examens = examens;
    }

    @Override
    public String toString() {
        return idG + "-" + libele ;
    }




}


