package gnots.models;
// Generated 9 f�vr. 2021 09:45:32 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Module generated by hbm2java
 */
@Entity
@Table(name="MODULE"
    ,schema="GNOTES"
)
public class Module  implements java.io.Serializable {


     private long idm;
     private String libele;
     private Set<Examen> examens = new HashSet<Examen>(0);

    public Module() {
    }

	
    public Module(long idm) {
        this.idm = idm;
    }
    public Module(long idm, String libele, Set<Examen> examens) {
       this.idm = idm;
       this.libele = libele;
       this.examens = examens;
    }
   
     @Id 

    
    @Column(name="IDM", unique=true, nullable=false, precision=10, scale=0)
    public long getIdm() {
        return this.idm;
    }
    
    public void setIdm(long idm) {
        this.idm = idm;
    }

    
    @Column(name="LIBELE", length=25)
    public String getLibele() {
        return this.libele;
    }
    
    public void setLibele(String libele) {
        this.libele = libele;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="module")
    public Set<Examen> getExamens() {
        return this.examens;
    }
    
    public void setExamens(Set<Examen> examens) {
        this.examens = examens;
    }

    @Override
    public String toString() {
        return   idm + " - " + libele ;
    }




}


