package gnots.models;
// Generated 8 f�vr. 2021 15:23:57 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Notes generated by hbm2java
 */
@Entity
@Table(name="NOTES"
    ,schema="GNOTES"
)
public class Notes  implements java.io.Serializable {


     private NotesId id;
     private Etudiant etudiant;
     private Examen examen;
     private float note;

    public Notes() {
    }

	
    public Notes(NotesId id, Etudiant etudiant, Examen examen) {
        this.id = id;
        this.etudiant = etudiant;
        this.examen = examen;
    }
    public Notes(NotesId id, Etudiant etudiant, Examen examen, float note) {
       this.id = id;
       this.etudiant = etudiant;
       this.examen = examen;
       this.note = note;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idEx", column=@Column(name="ID_EX", nullable=false, precision=10, scale=0) ), 
        @AttributeOverride(name="idE", column=@Column(name="ID_E", nullable=false, precision=10, scale=0) ) } )
    public NotesId getId() {
        return this.id;
    }
    
    public void setId(NotesId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_E", nullable=false, insertable=false, updatable=false)
    public Etudiant getEtudiant() {
        return this.etudiant;
    }
    
    public void setEtudiant(Etudiant etudiant) {
        this.etudiant = etudiant;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_EX", nullable=false, insertable=false, updatable=false)
    public Examen getExamen() {
        return this.examen;
    }
    
    public void setExamen(Examen examen) {
        this.examen = examen;
    }

    
    @Column(name="NOTE", precision=4)
    public float getNote() {
        return this.note;
    }
    
    public void setNote(float note) {
        this.note = note;
    }




}


