package gnots.models;
// Generated 9 f�vr. 2021 09:45:32 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Professeur generated by hbm2java
 */
@Entity
@Table(name="PROFESSEUR"
    ,schema="GNOTES"
)
public class Professeur  implements java.io.Serializable {


     private long idP;
     private String nomprof;
     private String prenomprof;
     private String specialite;
     private Set<Examen> examens = new HashSet<Examen>(0);

    public Professeur() {
    }

    @Override
    public String toString() {
        return  nomprof + " " + prenomprof + " - " + specialite + '}';
    }

	
    public Professeur(long idP) {
        this.idP = idP;
    }
    public Professeur(long idP, String nomprof, String prenomprof, String specialite, Set<Examen> examens) {
       this.idP = idP;
       this.nomprof = nomprof;
       this.prenomprof = prenomprof;
       this.specialite = specialite;
       this.examens = examens;
    }
   
     @Id 

    
    @Column(name="ID_P", unique=true, nullable=false, precision=10, scale=0)
    public long getIdP() {
        return this.idP;
    }
    
    public void setIdP(long idP) {
        this.idP = idP;
    }

    
    @Column(name="NOMPROF", length=25)
    public String getNomprof() {
        return this.nomprof;
    }
    
    public void setNomprof(String nomprof) {
        this.nomprof = nomprof;
    }

    
    @Column(name="PRENOMPROF", length=25)
    public String getPrenomprof() {
        return this.prenomprof;
    }
    
    public void setPrenomprof(String prenomprof) {
        this.prenomprof = prenomprof;
    }

    
    @Column(name="SPECIALITE", length=25)
    public String getSpecialite() {
        return this.specialite;
    }
    
    public void setSpecialite(String specialite) {
        this.specialite = specialite;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="professeur")
    public Set<Examen> getExamens() {
        return this.examens;
    }
    
    public void setExamens(Set<Examen> examens) {
        this.examens = examens;
    }




}


