/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestion.client;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author NeetKing
 */
public class FrmeClient extends javax.swing.JFrame {
   private ArrayList<Client> clts=new ArrayList<Client>();
   private int pos=0;
    /**
     * Creates new form FrmeClient
     */
    public FrmeClient() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtnoclt = new javax.swing.JTextField();
        txtnom = new javax.swing.JTextField();
        lblnoclt = new javax.swing.JLabel();
        lblnom = new javax.swing.JLabel();
        lblprenom = new javax.swing.JLabel();
        txtprenom = new javax.swing.JTextField();
        lbladresse = new javax.swing.JLabel();
        txtadresse = new javax.swing.JTextField();
        btnpremier = new javax.swing.JButton();
        btnprecedent = new javax.swing.JButton();
        btnsuivant = new javax.swing.JButton();
        btndernier = new javax.swing.JButton();
        btnsupprimer = new javax.swing.JButton();
        btnmodifier = new javax.swing.JButton();
        btnajouter = new javax.swing.JButton();
        btnnouveau = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblnoclt.setText("No Client");

        lblnom.setText("Nom Client");

        lblprenom.setText("Prenom Client");

        txtprenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprenomActionPerformed(evt);
            }
        });

        lbladresse.setText("Adresse Client");

        btnpremier.setText("|<");
        btnpremier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpremierActionPerformed(evt);
            }
        });

        btnprecedent.setText("<<");
        btnprecedent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprecedentActionPerformed(evt);
            }
        });

        btnsuivant.setText(">>");
        btnsuivant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuivantActionPerformed(evt);
            }
        });

        btndernier.setText(">|");
        btndernier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndernierActionPerformed(evt);
            }
        });

        btnsupprimer.setText("Supprimer");
        btnsupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsupprimerActionPerformed(evt);
            }
        });

        btnmodifier.setText("Modifier");
        btnmodifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodifierActionPerformed(evt);
            }
        });

        btnajouter.setText("Ajouter");
        btnajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnajouterActionPerformed(evt);
            }
        });

        btnnouveau.setText("Nouveau");
        btnnouveau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnouveauActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 51, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("ListCommande");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblnoclt)
                            .addComponent(lblprenom)
                            .addComponent(lblnom)
                            .addComponent(lbladresse))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtnoclt)
                            .addComponent(txtnom)
                            .addComponent(txtprenom)
                            .addComponent(txtadresse, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnpremier)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnprecedent)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnsuivant))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnnouveau)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnajouter)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnmodifier))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnsupprimer)
                            .addComponent(btndernier))))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnoclt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblnoclt))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblnom))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblprenom)
                    .addComponent(txtprenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbladresse)
                    .addComponent(txtadresse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnpremier)
                    .addComponent(btnprecedent)
                    .addComponent(btnsuivant)
                    .addComponent(btndernier))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsupprimer)
                    .addComponent(btnmodifier)
                    .addComponent(btnajouter)
                    .addComponent(btnnouveau))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtprenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprenomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprenomActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       try {
           // TODO add your handling code here:
           Connection con=MyUtil.seConnecter();
           Statement st=con.createStatement();
           ResultSet rs=st.executeQuery("select * from client");
           while(rs.next()){
               clts.add(new Client (rs.getInt(1),rs.getString(2),rs.getString(3),rs.getString(4)));
           }
           rs.close();
           con.close();
               
           afficher();
           
           
       } catch (Exception ex) {
           Logger.getLogger(FrmeClient.class.getName()).log(Level.SEVERE, null, ex);
       }
        
    }//GEN-LAST:event_formWindowOpened

    private void btnpremierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpremierActionPerformed
        // TODO add your handling code here:
        try{
        pos=0;
        afficher();
        }catch(IndexOutOfBoundsException e){
                JOptionPane.showMessageDialog(null, "list de  client vide");
                }
    }//GEN-LAST:event_btnpremierActionPerformed

    private void btnprecedentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprecedentActionPerformed
        // TODO add your handling code here:
         try{
        pos--;
        afficher();
        }catch(IndexOutOfBoundsException e){
                pos++;
                }
    }//GEN-LAST:event_btnprecedentActionPerformed

    private void btnsuivantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuivantActionPerformed
        // TODO add your handling code here:
         try{
        pos++;
        afficher();
        }catch(IndexOutOfBoundsException e){
                pos--;
                }
    }//GEN-LAST:event_btnsuivantActionPerformed

    private void btndernierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndernierActionPerformed
        // TODO add your handling code here:
         try{
        pos=clts.size()-1;
        afficher();
        }catch(IndexOutOfBoundsException e){
             JOptionPane.showMessageDialog(null, "list de  client vide");
                }
    }//GEN-LAST:event_btndernierActionPerformed

    private void btnnouveauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnouveauActionPerformed
        // TODO add your handling code here:
        
        txtnoclt.setText("");
        txtnom.setText("");
        txtprenom.setText("");
        txtadresse.setText("");
        
    }//GEN-LAST:event_btnnouveauActionPerformed

    private void btnajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnajouterActionPerformed
       try {
           // TODO add your handling code here:
           Connection con=MyUtil.seConnecter();
           PreparedStatement ps=con.prepareStatement("insert into client values(?,?,?,?)");
           int noclt=Integer.parseInt(txtnoclt.getText());
           String nom=txtnom.getText();
           String prenom=txtprenom.getText();
           String adresse=txtadresse.getText();
           Client c=new Client(noclt,nom,prenom,adresse);
           ps.setInt(1,noclt);
           ps.setString(2, nom);
           ps.setString(3, prenom);
           ps.setString(4, adresse);
           ps.executeUpdate();
           clts.add(c);
           JOptionPane.showMessageDialog(null,"client ajouter avec succes");
           
       } catch (Exception ex) {
           Logger.getLogger(FrmeClient.class.getName()).log(Level.SEVERE, null, ex);
       }
        
        
        
        
    }//GEN-LAST:event_btnajouterActionPerformed

    private void btnsupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsupprimerActionPerformed
        // TODO add your handling code here:
         
       try {
         Connection  con = MyUtil.seConnecter();
       
           PreparedStatement ps=con.prepareStatement("delete from client where noclt=?");
           Client c=clts.get(pos);
           ps.setInt(1,c.getNoclt());
           
          
           ps.executeUpdate();
           clts.remove(c);
           JOptionPane.showMessageDialog(null,"client supprimer avec succes");
           } catch (Exception ex) {
           Logger.getLogger(FrmeClient.class.getName()).log(Level.SEVERE, null, ex);
       }
    }//GEN-LAST:event_btnsupprimerActionPerformed

    private void btnmodifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodifierActionPerformed
        // TODO add your handling code here:
        try{
         Connection con=MyUtil.seConnecter();
           PreparedStatement ps=con.prepareStatement("update client set nom=?,prenom=?,adresse=? "+"where noclt=?");
           
           String nom=txtnom.getText();
           String prenom=txtprenom.getText();
           String adresse=txtadresse.getText();
           Client c=clts.get(pos);
           ps.setInt(4,c.getNoclt());
           ps.setString(1, nom);
           ps.setString(2, prenom);
           ps.setString(3, adresse);
           ps.executeUpdate();
           c.setNom(nom);
           c.setPrenom(prenom);
           c.setAdresse(adresse);
           JOptionPane.showMessageDialog(null,"client modifier avec succes");
           
       } catch (Exception ex) {
           Logger.getLogger(FrmeClient.class.getName()).log(Level.SEVERE, null, ex);
       }
    }//GEN-LAST:event_btnmodifierActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new frameCmdClient(clts.get(pos)).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmeClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmeClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmeClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmeClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmeClient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnajouter;
    private javax.swing.JButton btndernier;
    private javax.swing.JButton btnmodifier;
    private javax.swing.JButton btnnouveau;
    private javax.swing.JButton btnprecedent;
    private javax.swing.JButton btnpremier;
    private javax.swing.JButton btnsuivant;
    private javax.swing.JButton btnsupprimer;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lbladresse;
    private javax.swing.JLabel lblnoclt;
    private javax.swing.JLabel lblnom;
    private javax.swing.JLabel lblprenom;
    private javax.swing.JTextField txtadresse;
    private javax.swing.JTextField txtnoclt;
    private javax.swing.JTextField txtnom;
    private javax.swing.JTextField txtprenom;
    // End of variables declaration//GEN-END:variables

    private void afficher() {
   Client clt=clts.get(pos);
   txtnoclt.setText(clt.getNoclt()+"");
   txtnom.setText(clt.getNom());
   txtprenom.setText(clt.getPrenom());
   txtadresse.setText(clt.getAdresse());
   
   
    }
}
