package hebernat;
// Generated Feb 3, 2022 3:08:52 PM by Hibernate Tools 4.3.1



/**
 * Detailcom generated by hbm2java
 */
public class Detailcom  implements java.io.Serializable {


     private DetailcomId id;
     private Commande commande;
     private Article article;
     private Long qtecpmd;

    public Detailcom() {
    }

	
    public Detailcom(DetailcomId id, Commande commande, Article article) {
        this.id = id;
        this.commande = commande;
        this.article = article;
    }
    public Detailcom(DetailcomId id, Commande commande, Article article, Long qtecpmd) {
       this.id = id;
       this.commande = commande;
       this.article = article;
       this.qtecpmd = qtecpmd;
    }
   
    public DetailcomId getId() {
        return this.id;
    }
    
    public void setId(DetailcomId id) {
        this.id = id;
    }
    public Commande getCommande() {
        return this.commande;
    }
    
    public void setCommande(Commande commande) {
        this.commande = commande;
    }
    public Article getArticle() {
        return this.article;
    }
    
    public void setArticle(Article article) {
        this.article = article;
    }
    public Long getQtecpmd() {
        return this.qtecpmd;
    }
    
    public void setQtecpmd(Long qtecpmd) {
        this.qtecpmd = qtecpmd;
    }




}


