/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg.views;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pkg.dao.MyUtil;
import pkg.models.Voiture;

/**
 *
 * @author user
 */
public class CarFrame extends javax.swing.JInternalFrame {

    int pos = 0;
    ArrayList<Voiture> lv = new ArrayList<Voiture>();
    DefaultTableModel df = null;

    /**
     * Creates new form CarFrame
     */
    public CarFrame() {
        initComponents();
        df = (DefaultTableModel) jTable1.getModel();
        df.setRowCount(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtMatricule = new javax.swing.JTextField();
        txtMarque = new javax.swing.JTextField();
        txtCouleur = new javax.swing.JTextField();
        txtPrix = new javax.swing.JTextField();
        rdbtnEnServ = new javax.swing.JRadioButton();
        rdbtnHorsServ = new javax.swing.JRadioButton();
        cbxCarburant = new javax.swing.JComboBox<>();
        btnPremier = new javax.swing.JButton();
        btnPreced = new javax.swing.JButton();
        btnSuiv = new javax.swing.JButton();
        btnDernier = new javax.swing.JButton();
        txtModel = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnAjout = new javax.swing.JButton();
        btnSupp = new javax.swing.JButton();
        btnMod = new javax.swing.JButton();
        btnNew = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        txtMatRech = new javax.swing.JTextField();
        btnMatRech = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Gerer les Voitures");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Voitures", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 14))); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(475, 381));

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel1.setText("Matricule : ");

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel2.setText("Model : ");

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel3.setText("Marque : ");

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel4.setText("Couleur : ");

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel5.setText("Carburant : ");

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel6.setText("Etat : ");

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel7.setText("Prix/jour : ");

        txtMatricule.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        txtMarque.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        txtCouleur.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        txtPrix.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        buttonGroup1.add(rdbtnEnServ);
        rdbtnEnServ.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        rdbtnEnServ.setText("En service");

        buttonGroup1.add(rdbtnHorsServ);
        rdbtnHorsServ.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        rdbtnHorsServ.setText("Hors service");

        cbxCarburant.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        cbxCarburant.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Diesel", "Essance", "Hybride", "Electriques" }));

        btnPremier.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnPremier.setText("|<");
        btnPremier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPremierActionPerformed(evt);
            }
        });

        btnPreced.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnPreced.setText("<<");
        btnPreced.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrecedActionPerformed(evt);
            }
        });

        btnSuiv.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnSuiv.setText(">>");
        btnSuiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuivActionPerformed(evt);
            }
        });

        btnDernier.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnDernier.setText(">|");
        btnDernier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDernierActionPerformed(evt);
            }
        });

        txtModel.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("NOTE: vous devez selectionez votre voiture au decus avons une suppresion ou une modification.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtMatricule))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtMarque))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtPrix))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtCouleur))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cbxCarburant, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(rdbtnEnServ)
                                .addGap(18, 18, 18)
                                .addComponent(rdbtnHorsServ)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtModel))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addComponent(btnPremier)
                                .addGap(18, 18, 18)
                                .addComponent(btnPreced)
                                .addGap(18, 18, 18)
                                .addComponent(btnSuiv)
                                .addGap(18, 18, 18)
                                .addComponent(btnDernier))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel9)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMatricule, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMarque, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCouleur, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxCarburant, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdbtnEnServ)
                    .addComponent(rdbtnHorsServ))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrix, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPremier)
                    .addComponent(btnPreced)
                    .addComponent(btnSuiv)
                    .addComponent(btnDernier))
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gerer Voitures", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 14))); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(534, 88));

        btnAjout.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnAjout.setText("Ajouter");
        btnAjout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjoutActionPerformed(evt);
            }
        });

        btnSupp.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnSupp.setText("Supprimer");
        btnSupp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuppActionPerformed(evt);
            }
        });

        btnMod.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnMod.setText("Modifier");
        btnMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModActionPerformed(evt);
            }
        });

        btnNew.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnNew.setText("Nouveau");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAjout, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSupp, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMod, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAjout, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSupp, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMod, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Liste des Voitures", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 14))); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Matricule", "Model", "Marque", "Couleur", "Carburant", "Etat", "Prix/jour"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel8.setText("Rechercher par Matricule : ");

        txtMatRech.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        btnMatRech.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkg/imgs/search_30px.png"))); // NOI18N
        btnMatRech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMatRechActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 886, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMatRech, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMatRech, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnMatRech, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtMatRech, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPremierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPremierActionPerformed
        // TODO add your handling code here:
        try {
            pos = 0;
            afficher();
        } catch (IndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(null, "List des voitures est vide");
        }
    }//GEN-LAST:event_btnPremierActionPerformed

    private void btnPrecedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrecedActionPerformed
        // TODO add your handling code here:
        try {
            pos--;
            afficher();
        } catch (IndexOutOfBoundsException e) {
            pos++;
        }
    }//GEN-LAST:event_btnPrecedActionPerformed

    private void btnSuivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuivActionPerformed
        // TODO add your handling code here:
        try {
            pos++;
            afficher();
        } catch (IndexOutOfBoundsException e) {
            pos--;
        }
    }//GEN-LAST:event_btnSuivActionPerformed

    private void btnDernierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDernierActionPerformed
        // TODO add your handling code here:
        try {
            pos = lv.size() - 1;
            afficher();
        } catch (IndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(null, "List des voitures est vide");
        }
    }//GEN-LAST:event_btnDernierActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        try {
            // TODO add your handling code here:
            Connection conn = MyUtil.seConnecter();
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery("select * from voiture");
            while (rs.next()) {
                lv.add(new Voiture(rs.getString(1), rs.getInt(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getString(6), rs.getFloat(7)));
            }
            rs.close();
            st.close();
            conn.close();
            afficher();
            for (Voiture v : lv) {
                df.addRow(new Object[]{v.getMatricule(), v.getModel(), v.getMarque(), v.getCouleur(), v.getCarburant(), v.getEtat(), v.getPrix()});
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "erreur" + ex.getMessage());
        }
    }//GEN-LAST:event_formInternalFrameOpened

    private void btnAjoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjoutActionPerformed
        try {
            // TODO add your handling code here:
            Voiture v = new Voiture();
            v.setMatricule(txtMatricule.getText());
            v.setModel(Integer.parseInt(txtModel.getText()));
            v.setMarque(txtMarque.getText());
            v.setCouleur(txtCouleur.getText());
            v.setCarburant((String) cbxCarburant.getSelectedItem());
            if (rdbtnEnServ.isSelected()) {
                v.setEtat("En service");
            } else {
                v.setEtat("Hors service");
            }
            v.setPrix(Float.parseFloat(txtPrix.getText()));

            Connection conn = MyUtil.seConnecter();
            PreparedStatement ps = conn.prepareStatement("insert into voiture values(?,?,?,?,?,?,?)");
            ps.setString(1, v.getMatricule());
            ps.setString(2, v.getModel() + "");
            ps.setString(3, v.getMarque());
            ps.setString(4, v.getCouleur());
            ps.setString(5, v.getCarburant());
            ps.setString(6, v.getEtat());
            ps.setString(7, v.getPrix() + "");
            ps.executeUpdate();
            ps.close();
            conn.close();
            lv.add(v);
            df.addRow(new Object[]{v.getMatricule(), v.getModel(), v.getMarque(), v.getCouleur(), v.getCarburant(), v.getEtat(), v.getPrix()});
            JOptionPane.showMessageDialog(null, "Voiture ajouté avec succes.");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "erreur" + ex.getMessage());
        }

    }//GEN-LAST:event_btnAjoutActionPerformed

    private void btnSuppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuppActionPerformed
        try {
            // TODO add your handling code here:
            Voiture v = lv.get(pos);
            Connection conn = MyUtil.seConnecter();
            PreparedStatement ps = conn.prepareStatement("delete from voiture where matricule=?");
            ps.setString(1, v.getMatricule());
            ps.executeUpdate();

            try {
                lv.remove(v);
                df.removeRow(pos);
                pos--;
                afficher();
            } catch (IndexOutOfBoundsException ex) {
                pos++;
                afficher();
            }

            if (lv.isEmpty()) {
                txtMatricule.setText("");
                txtMarque.setText("");
                txtCouleur.setText("");
                txtPrix.setText("");
                txtModel.setText("");
                cbxCarburant.setSelectedItem("");
                rdbtnEnServ.setSelected(false);
                rdbtnHorsServ.setSelected(false);
            }
            JOptionPane.showMessageDialog(null, "Voiture supprimé avec succes");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "" + ex.getMessage());
        }
    }//GEN-LAST:event_btnSuppActionPerformed

    private void btnModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModActionPerformed
        try {
            // TODO add your handling code here:
            Voiture v = lv.get(pos);
            v.setMatricule(txtMatricule.getText());
            v.setModel(Integer.parseInt(txtModel.getText()));
            v.setMarque(txtMarque.getText());
            v.setCouleur(txtCouleur.getText());
            v.setCarburant((String) cbxCarburant.getSelectedItem());
            if (rdbtnEnServ.isSelected()) {
                v.setEtat("En service");
            } else {
                v.setEtat("Hors service");
            }

            Connection conn = MyUtil.seConnecter();
            PreparedStatement ps = conn.prepareStatement("update voiture set model=?,marque=?,couleur=?,carburant=?,etat=?,prix=? where matricule=?");
            ps.setInt(1, v.getModel());
            ps.setString(2, v.getMarque());
            ps.setString(3, v.getCouleur());
            ps.setString(4, v.getCarburant());
            ps.setString(5, v.getEtat());
            ps.setString(6, v.getPrix() + "");
            ps.setString(7, v.getMatricule());
            ps.executeUpdate();
            ps.close();
            conn.close();

            df.setValueAt(v.getMatricule(), pos, 0);
            df.setValueAt(v.getModel(), pos, 1);
            df.setValueAt(v.getMarque(), pos, 2);
            df.setValueAt(v.getCouleur(), pos, 3);
            df.setValueAt(v.getCarburant(), pos, 4);
            df.setValueAt(v.getEtat(), pos, 5);
            df.setValueAt(v.getPrix(), pos, 6);

            JOptionPane.showMessageDialog(null, "Voiture modifié avec succes.");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "erreur" + ex.getMessage());
        }
    }//GEN-LAST:event_btnModActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        // TODO add your handling code here:
        txtMatricule.setText("");
        txtModel.setText("");
        txtMarque.setText("");
        txtCouleur.setText("");
        cbxCarburant.setSelectedItem(null);
        txtPrix.setText("");
        rdbtnEnServ.setSelected(false);
        rdbtnHorsServ.setSelected(false);
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnMatRechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMatRechActionPerformed
        // TODO add your handling code here:
        Voiture v = new Voiture();
        int id = 0;
        String mat = txtMatRech.getText();
        try {
            Connection conn = MyUtil.seConnecter();
            PreparedStatement ps = conn.prepareStatement("select matricule,model,marque,couleur,carburant,etat,prix from voiture where matricule = '" + mat + "'");
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                id = 1;
                txtMatricule.setText(rs.getString(1));
                txtModel.setText(rs.getInt(2) + "");
                txtMarque.setText(rs.getString(3));
                txtCouleur.setText(rs.getString(4));
                cbxCarburant.setSelectedItem(rs.getString(5));
                if (rs.getString(6).equals("En service")) {
                    rdbtnEnServ.setSelected(true);
                } else {
                    rdbtnHorsServ.setSelected(true);
                }
                txtPrix.setText(rs.getFloat(7) + "");
            }
            if(id == 0) {
                JOptionPane.showMessageDialog(null, "Matricule Introuvable !");
                txtMatricule.setText(null);
                txtModel.setText(null);
                txtMarque.setText(null);
                txtCouleur.setText(null);
                cbxCarburant.setSelectedItem(null);
                rdbtnEnServ.setSelected(false);
                rdbtnHorsServ.setSelected(false);
                txtPrix.setText(null);
            }
        } catch (Exception ex) {
            Logger.getLogger(CarFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnMatRechActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjout;
    private javax.swing.JButton btnDernier;
    private javax.swing.JButton btnMatRech;
    private javax.swing.JButton btnMod;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnPreced;
    private javax.swing.JButton btnPremier;
    private javax.swing.JButton btnSuiv;
    private javax.swing.JButton btnSupp;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbxCarburant;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton rdbtnEnServ;
    private javax.swing.JRadioButton rdbtnHorsServ;
    private javax.swing.JTextField txtCouleur;
    private javax.swing.JTextField txtMarque;
    private javax.swing.JTextField txtMatRech;
    private javax.swing.JTextField txtMatricule;
    private javax.swing.JTextField txtModel;
    private javax.swing.JTextField txtPrix;
    // End of variables declaration//GEN-END:variables

    private void afficher() {
        if (lv.size() > 0) {
            Voiture v = lv.get(pos);
            txtMatricule.setText(v.getMatricule());
            txtModel.setText(v.getModel() + "");
            txtMarque.setText(v.getMarque());
            txtCouleur.setText(v.getCouleur());
            cbxCarburant.setSelectedItem(v.getCarburant());
            if (v.getEtat().equals("En service")) {
                rdbtnEnServ.setSelected(true);
            } else {
                rdbtnHorsServ.setSelected(true);
            }
            txtPrix.setText(v.getPrix() + "");
        }
    }
}
