/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg.views;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.time.Duration;
import java.util.ArrayList;
import java.util.HashMap;
import static java.util.concurrent.TimeUnit.DAYS;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.swing.JRViewer;
import pkg.dao.MyUtil;
import pkg.models.Client;
import pkg.models.Contrat;
import pkg.models.Voiture;

/**
 *
 * @author user
 */
public class ContractFrame extends javax.swing.JInternalFrame {

    ArrayList<Contrat> lc = new ArrayList<>();
    ArrayList<Voiture> lv = new ArrayList<>();
    ArrayList<Client> lclt = new ArrayList<>();
    int pos = 0;
    DefaultTableModel df = null;

    /**
     * Creates new form ContractFrame
     */
    public ContractFrame() {
        initComponents();
        df = (DefaultTableModel) jTable1.getModel();
        df.setRowCount(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtIDContrat = new javax.swing.JTextField();
        txtMontant = new javax.swing.JTextField();
        DateDep = new com.toedter.calendar.JDateChooser();
        DateRetour = new com.toedter.calendar.JDateChooser();
        btnAjouter = new javax.swing.JButton();
        btnSupp = new javax.swing.JButton();
        btnModifier = new javax.swing.JButton();
        btnNouveau = new javax.swing.JButton();
        cbxMatricule = new javax.swing.JComboBox<>();
        cbxCINC = new javax.swing.JComboBox<>();
        lblMat = new javax.swing.JLabel();
        lblCIN = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtIDContratRech = new javax.swing.JTextField();
        txtCINRech = new javax.swing.JTextField();
        btnRechID = new javax.swing.JButton();
        btnRechCIN = new javax.swing.JButton();
        btnImprimer = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Contrats");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 14))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel1.setText("ID Contrat : ");

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel2.setText("Date Depart : ");

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel3.setText("Date Retour : ");

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel4.setText("Montant : ");

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel5.setText("Matricule : ");

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel6.setText("CIN Client : ");

        txtIDContrat.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtIDContrat.setEnabled(false);
        txtIDContrat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDContratActionPerformed(evt);
            }
        });

        txtMontant.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        DateDep.setDateFormatString("dd-MMM-yyyy");
        DateDep.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        DateRetour.setDateFormatString("dd-MMM-yyyy");
        DateRetour.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        btnAjouter.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnAjouter.setText("Ajouter");
        btnAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterActionPerformed(evt);
            }
        });

        btnSupp.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnSupp.setText("Supprimer");
        btnSupp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuppActionPerformed(evt);
            }
        });

        btnModifier.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnModifier.setText("Modifier Date/Montant");
        btnModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifierActionPerformed(evt);
            }
        });

        btnNouveau.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnNouveau.setText("Nouveau");
        btnNouveau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNouveauActionPerformed(evt);
            }
        });

        cbxMatricule.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        cbxMatricule.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxMatriculeItemStateChanged(evt);
            }
        });

        cbxCINC.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        lblMat.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        lblCIN.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtIDContrat)
                    .addComponent(txtMontant)
                    .addComponent(DateDep, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                    .addComponent(DateRetour, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxMatricule, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxCINC, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblMat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCIN, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSupp, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnModifier)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNouveau, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIDContrat, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DateDep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DateRetour, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMontant, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblMat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                            .addComponent(cbxMatricule, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxCINC, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(lblCIN, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSupp, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModifier, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNouveau, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Rechercher Contrat", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 14))); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Contrat", "Date Depart", "Date Retour", "Montant", "Matricule", "CIN Client"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel7.setText("ID Contrat : ");

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel8.setText("CIN Client : ");

        txtIDContratRech.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        txtCINRech.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        btnRechID.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkg/imgs/search_30px.png"))); // NOI18N
        btnRechID.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btnRechIDItemStateChanged(evt);
            }
        });
        btnRechID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRechIDActionPerformed(evt);
            }
        });

        btnRechCIN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkg/imgs/search_30px.png"))); // NOI18N
        btnRechCIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRechCINActionPerformed(evt);
            }
        });

        btnImprimer.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnImprimer.setText("Imprimer Contrat");
        btnImprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIDContratRech, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRechID, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(txtCINRech, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRechCIN, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(323, 323, 323)
                .addComponent(btnImprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(btnRechID, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRechCIN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtIDContratRech, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtCINRech, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnImprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterActionPerformed
        try {
            // TODO add your handling code here:
            Contrat c = new Contrat();
            Voiture v = (Voiture) cbxMatricule.getSelectedItem();
            Client clt = (Client) cbxCINC.getSelectedItem();
            SimpleDateFormat sdf = new SimpleDateFormat("dd-MMM-yyyy");
            String dateD = sdf.format(DateDep.getDate());
            String dateR = sdf.format(DateRetour.getDate());
            c.setMontant(Float.parseFloat(txtMontant.getText()));

            Connection conn = MyUtil.seConnecter();
            PreparedStatement ps = conn.prepareStatement("insert into contrat values(SEQ_IDCONTRAT.NEXTVAL,?,?,?,?,?)", new int[]{1});

            ps.setString(1, dateD);
            ps.setString(2, dateR);
            ps.setFloat(3, c.getMontant());
            ps.setString(4, v.getMatricule());
            ps.setString(5, clt.getCin_clt());
            ps.executeUpdate();
            ResultSet rs = ps.getGeneratedKeys();
            rs.next();
            Contrat co = new Contrat(rs.getInt(1), DateDep.getDate(), DateRetour.getDate(), c.getMontant(), v.getMatricule(), clt.getCin_clt());
            ps.close();
            conn.close();
            lc.add(c);
            df.addRow(new Object[]{co.getIdContrat(), sdf.format(DateDep.getDate()), sdf.format(DateRetour.getDate()), co.getMontant(), v.getMatricule(), clt.getCin_clt()});

            Connection conn1 = MyUtil.seConnecter();
            PreparedStatement ps1 = conn1.prepareStatement("update Voiture set etat = 'Hors service' where matricule = '" + v.getMatricule() + "'");
            ps1.executeUpdate();
            ps1.close();
            conn1.close();

            JOptionPane.showMessageDialog(null, "Contrat Ajouté Avec Succes !");
        } catch (Exception ex) {
            Logger.getLogger(ContractFrame.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btnAjouterActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        try {
            // TODO add your handling code here:
            Connection con = MyUtil.seConnecter();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select * from voiture where etat = 'En service'");
            while (rs.next()) {
                cbxMatricule.addItem(new Voiture(rs.getString(1), rs.getInt(2), rs.getString(3), rs.getString(4),
                        rs.getString(5), rs.getString(6), rs.getFloat(7)));
            }
            rs.close();
            ResultSet rs1 = st.executeQuery("select * from client");
            while (rs1.next()) {
                cbxCINC.addItem(new Client(rs1.getString(1), rs1.getString(2), rs1.getString(3), rs1.getString(4), rs1.getString(5), rs1.getString(6)));
            }
            rs1.close();

            ResultSet rs2 = st.executeQuery("select id_contrat,date_d,date_r,montant,matricule,cin_clt from contrat order by id_contrat desc");
            while (rs2.next()) {
                df.addRow(new Object[]{rs2.getInt("id_contrat"), rs2.getDate("date_d"), rs2.getDate("date_r"), rs2.getFloat("montant"), rs2.getString("matricule"), rs2.getString("cin_clt")});
            }
        } catch (Exception ex) {
            Logger.getLogger(ContractFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formInternalFrameOpened

    private void btnSuppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuppActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "voulez-vous vraiment supprimer cette Contrat !", "selectioner", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            try {
                Voiture v = new Voiture();
                Contrat c = new Contrat();
                String mat = lblMat.getText();
                String id = txtIDContratRech.getText();
                Connection con = MyUtil.seConnecter();
                Statement st = con.createStatement();
                st.executeUpdate("delete from contrat where id_contrat = '" + id + "'");
                JOptionPane.showMessageDialog(null, "Contrat Supprimé avec succes");
                Connection conn1 = MyUtil.seConnecter();
                PreparedStatement ps1 = conn1.prepareStatement("update Voiture set etat = 'En service' where matricule = '" + mat + "'");
                ps1.executeUpdate();
                ps1.close();
                conn1.close();
                lc.remove(c);
                df.removeRow(pos);
            } catch (Exception ex) {
                Logger.getLogger(ContractFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnSuppActionPerformed

    private void btnRechIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRechIDActionPerformed
        try {
            // TODO add your handling code here:
            int id = 0;
            String idc = txtIDContratRech.getText();
            Connection con = MyUtil.seConnecter();
            PreparedStatement ps = con.prepareStatement("select id_contrat,date_d,date_r,montant,matricule,cin_clt from contrat where id_contrat = '" + idc + "'");
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                id = 1;
                txtIDContrat.setText(rs.getInt(1) + "");
                DateDep.setDate(rs.getDate(2));
                DateRetour.setDate(rs.getDate(3));
                txtMontant.setText(rs.getFloat(4) + "");
                lblMat.setText(rs.getString(5));
                lblCIN.setText(rs.getString(6));
                cbxCINC.setSelectedItem(null);
                cbxMatricule.setSelectedItem(null);
            }
            if (id == 0) {
                JOptionPane.showMessageDialog(null, "ID Invalide !");
                txtIDContrat.setText(null);
                txtCINRech.setText(null);
                txtIDContratRech.setText(null);
                txtMontant.setText(null);
                lblCIN.setText(null);
                lblMat.setText(null);
                cbxCINC.setSelectedItem(null);
                cbxMatricule.setSelectedItem(null);
                DateDep.setDate(null);
                DateRetour.setDate(null);
            }
        } catch (Exception ex) {
            Logger.getLogger(ContractFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRechIDActionPerformed

    private void btnRechIDItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btnRechIDItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRechIDItemStateChanged

    private void cbxMatriculeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxMatriculeItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxMatriculeItemStateChanged

    private void btnRechCINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRechCINActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            int id = 0;
            String cin = txtCINRech.getText();
            Connection con = MyUtil.seConnecter();
            PreparedStatement ps = con.prepareStatement("select id_contrat,date_d,date_r,montant,matricule,cin_clt from contrat where cin_clt = '" + cin + "'");
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                id = 1;
                txtIDContrat.setText(rs.getInt(1) + "");
                DateDep.setDate(rs.getDate(2));
                DateRetour.setDate(rs.getDate(3));
                txtMontant.setText(rs.getFloat(4) + "");
                lblMat.setText(rs.getString(5));
                lblCIN.setText(rs.getString(6));
                cbxCINC.setSelectedItem(null);
                cbxMatricule.setSelectedItem(null);
            } if (id == 0) {
                JOptionPane.showMessageDialog(null, "CIN Invalide !");
                txtIDContrat.setText(null);
                txtCINRech.setText(null);
                txtIDContratRech.setText(null);
                txtMontant.setText(null);
                lblCIN.setText(null);
                lblMat.setText(null);
                cbxCINC.setSelectedItem(null);
                cbxMatricule.setSelectedItem(null);
                DateDep.setDate(null);
                DateRetour.setDate(null);
            }
        } catch (Exception ex) {
            Logger.getLogger(ContractFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRechCINActionPerformed

    private void btnModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierActionPerformed
        // TODO add your handling code here:
        String id = txtIDContrat.getText();
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MMM-yyyy");
        String dateR = sdf.format(DateRetour.getDate());
        String montant = txtMontant.getText();
        try {
            Connection con = MyUtil.seConnecter();
            PreparedStatement ps = con.prepareStatement("update contrat set date_r = ?, montant = ? where id_contrat = '" + id + "'");
            ps.setString(1, dateR);
            ps.setString(2, montant);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Modifié Avec Succes !");
        } catch (Exception ex) {
            Logger.getLogger(ContractFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnModifierActionPerformed

    private void btnNouveauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNouveauActionPerformed
        // TODO add your handling code here:
        txtIDContrat.setText(null);
        txtCINRech.setText(null);
        txtIDContratRech.setText(null);
        txtMontant.setText(null);
        lblCIN.setText(null);
        lblMat.setText(null);
        cbxCINC.setSelectedItem(null);
        cbxMatricule.setSelectedItem(null);
        DateDep.setDate(null);
        DateRetour.setDate(null);
    }//GEN-LAST:event_btnNouveauActionPerformed

    private void btnImprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimerActionPerformed
        try {
            // TODO add your handling code here:
            JasperDesign jd = JRXmlLoader.load("C:\\Users\\ABDOU\\Documents\\NetBeansProjects\\PFE2\\src\\pkg\\views\\MyEtat.jrxml");
            JasperReport jr = JasperCompileManager.compileReport(jd);
            HashMap param = new HashMap();
            param.put("p_idc", Integer.parseInt(txtIDContrat.getText()));
            JasperPrint jp = JasperFillManager.fillReport(jr, param, MyUtil.seConnecter());
            JRViewer viewer = new JRViewer(jp);
            Impression i = new Impression();
            i.getContentPane().add(viewer);
        } catch (JRException ex) {
            Logger.getLogger(ContractFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(ContractFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnImprimerActionPerformed

    private void txtIDContratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDContratActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDContratActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser DateDep;
    private com.toedter.calendar.JDateChooser DateRetour;
    private javax.swing.JButton btnAjouter;
    private javax.swing.JButton btnImprimer;
    private javax.swing.JButton btnModifier;
    private javax.swing.JButton btnNouveau;
    private javax.swing.JButton btnRechCIN;
    private javax.swing.JButton btnRechID;
    private javax.swing.JButton btnSupp;
    private javax.swing.JComboBox<Client> cbxCINC;
    private javax.swing.JComboBox<Voiture> cbxMatricule;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblCIN;
    private javax.swing.JLabel lblMat;
    private javax.swing.JTextField txtCINRech;
    private javax.swing.JTextField txtIDContrat;
    private javax.swing.JTextField txtIDContratRech;
    private javax.swing.JTextField txtMontant;
    // End of variables declaration//GEN-END:variables
}
