/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg.views;

import java.awt.image.BufferedImage;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pkg.dao.MyUtil;
import pkg.models.Employer;
import sun.applet.Main;

/**
 *
 * @author user
 */
public class EmployeesFrame extends javax.swing.JInternalFrame {
    ArrayList<Employer> le = new ArrayList<>();
    DefaultTableModel df = null;
    int pos = 0;

    /**
     * Creates new form EmplyeesFrame
     */
    public EmployeesFrame() {
        initComponents();
        df=(DefaultTableModel)jTable1.getModel();
        df.setRowCount(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnPremier = new javax.swing.JButton();
        btnPreced = new javax.swing.JButton();
        btnSuiv = new javax.swing.JButton();
        btnDernier = new javax.swing.JButton();
        txtCinE = new javax.swing.JTextField();
        txtNomE = new javax.swing.JTextField();
        txtPrnmE = new javax.swing.JTextField();
        txtAddrssE = new javax.swing.JTextField();
        txtTelE = new javax.swing.JTextField();
        cbxFonction = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        btnAjout = new javax.swing.JButton();
        btnSupp = new javax.swing.JButton();
        btnMod = new javax.swing.JButton();
        btnNew = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        txtCINRech = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Gerer les Employes");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/pkg/imgs/name_tag_50px.png"))); // NOI18N
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Employees", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 14))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel1.setText("CIN : ");

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel2.setText("Nom : ");

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel3.setText("Prenom : ");

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel4.setText("Adresse : ");

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel5.setText("Tel : ");

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel6.setText("Fonction : ");

        btnPremier.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnPremier.setText("|<");
        btnPremier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPremierActionPerformed(evt);
            }
        });

        btnPreced.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnPreced.setText("<<");
        btnPreced.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrecedActionPerformed(evt);
            }
        });

        btnSuiv.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnSuiv.setText(">>");
        btnSuiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuivActionPerformed(evt);
            }
        });

        btnDernier.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnDernier.setText(">|");
        btnDernier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDernierActionPerformed(evt);
            }
        });

        txtCinE.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        txtNomE.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        txtPrnmE.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        txtAddrssE.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        txtTelE.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        cbxFonction.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        cbxFonction.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Securite", "Menage", "Mecanicien", "Autre" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCinE, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNomE, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPrnmE, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAddrssE, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTelE, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbxFonction, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(btnPremier)
                        .addGap(18, 18, 18)
                        .addComponent(btnPreced)
                        .addGap(18, 18, 18)
                        .addComponent(btnSuiv)
                        .addGap(18, 18, 18)
                        .addComponent(btnDernier)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCinE, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomE, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrnmE, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAddrssE, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelE, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxFonction, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPremier)
                    .addComponent(btnPreced)
                    .addComponent(btnSuiv)
                    .addComponent(btnDernier))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gerer Employees", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 14))); // NOI18N

        btnAjout.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnAjout.setText("Ajouter");
        btnAjout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjoutActionPerformed(evt);
            }
        });

        btnSupp.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnSupp.setText("Supprimer");
        btnSupp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuppActionPerformed(evt);
            }
        });

        btnMod.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnMod.setText("Modifier");
        btnMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModActionPerformed(evt);
            }
        });

        btnNew.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnNew.setText("Nouveau");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAjout, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSupp, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMod, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAjout, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSupp, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMod, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Liste des Employees", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 14))); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CIN", "Nom", "Prenom", "Adresse", "Tel", "Fonction"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel7.setText("Rechercher par CIN Emp : ");

        txtCINRech.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkg/imgs/search_30px.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 870, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCINRech, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCINRech, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPremierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPremierActionPerformed
        // TODO add your handling code here:
        try{
            pos=0;
            afficher();
        }catch(IndexOutOfBoundsException e){
            JOptionPane.showMessageDialog(null, "List des client est vide");
        }
    }//GEN-LAST:event_btnPremierActionPerformed

    private void btnPrecedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrecedActionPerformed
        // TODO add your handling code here:
        try{
            pos--;
            afficher();
        }catch(IndexOutOfBoundsException e){
            pos++;
        }
    }//GEN-LAST:event_btnPrecedActionPerformed

    private void btnSuivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuivActionPerformed
        // TODO add your handling code here:
        try{
            pos++;
            afficher();
        }catch(IndexOutOfBoundsException e){
            pos--;
        }
    }//GEN-LAST:event_btnSuivActionPerformed

    private void btnDernierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDernierActionPerformed
        // TODO add your handling code here:
        try{
            pos=le.size()-1;
            afficher();
        }catch(IndexOutOfBoundsException e){
            JOptionPane.showMessageDialog(null, "List des Employees est vide");
        }
    }//GEN-LAST:event_btnDernierActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        try {
            // TODO add your handling code here:
            Connection conn = MyUtil.seConnecter();
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery("select * from employer");
            while(rs.next()) {
                le.add(new Employer(rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6)));
            }
            rs.close();
            st.close();
            conn.close();
            afficher();
            for(Employer e:le) {
                df.addRow(new Object[] {e.getCin_emp(),e.getNom_emp(),e.getPrenom_emp(),e.getAdresse_emp(),e.getTel(),e.getFonction()});
            }
        } catch (Exception ex) {
            Logger.getLogger(EmployeesFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_formInternalFrameOpened

    private void btnAjoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjoutActionPerformed
        try {
            // TODO add your handling code here:
            Employer e = new Employer();
            e.setCin_emp(txtCinE.getText());
            e.setNom_emp(txtNomE.getText());
            e.setPrenom_emp(txtPrnmE.getText());
            e.setAdresse_emp(txtAddrssE.getText());
            e.setTel(txtTelE.getText());
            e.setFonction(cbxFonction.getSelectedItem().toString());

            Connection conn = MyUtil.seConnecter();
            PreparedStatement ps = conn.prepareStatement("insert into employer values(?,?,?,?,?,?)");
            ps.setString(1, e.getCin_emp());
            ps.setString(2, e.getNom_emp());
            ps.setString(3, e.getPrenom_emp());
            ps.setString(4, e.getAdresse_emp());
            ps.setString(5, e.getTel());
            ps.setString(6, e.getFonction());
            ps.executeUpdate();
            ps.close();
            conn.close();
            le.add(e);
            df.addRow(new Object[] {e.getCin_emp(),e.getNom_emp(),e.getPrenom_emp(),e.getAdresse_emp(),e.getTel(),e.getFonction()});
            JOptionPane.showMessageDialog(null, "employer ajouté avec succes.");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "erreur"+ex.getMessage());
        }

    }//GEN-LAST:event_btnAjoutActionPerformed

    private void btnSuppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuppActionPerformed
        try {
            // TODO add your handling code here:
            Employer e = le.get(pos);
            Connection conn = MyUtil.seConnecter();
            PreparedStatement ps = conn.prepareStatement("delete from employer where cin_emp = ?");
            ps.setString(1, e.getCin_emp());
            ps.executeUpdate();
            ps.close();
            conn.close();

            try{
                le.remove(e);
                df.removeRow(pos);
                pos--;
                afficher();
            }catch(IndexOutOfBoundsException ex){
                pos++;
                afficher();
            }

            if(le.isEmpty()) {
                txtCinE.setText("");
                txtNomE.setText("");
                txtPrnmE.setText("");
                txtAddrssE.setText("");
                txtTelE.setText("");
                cbxFonction.setSelectedItem(null);
            }
            JOptionPane.showMessageDialog(null, "Employer supprimé avec succes");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "erreur"+ex.getMessage());
        }
    }//GEN-LAST:event_btnSuppActionPerformed

    private void btnModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModActionPerformed
        try {
            // TODO add your handling code here:
            // String fct = cbxFonction.getSelectedItem().toString();
            Employer e = le.get(pos);
            e.setNom_emp(txtNomE.getText());
            e.setPrenom_emp(txtPrnmE.getText());
            e.setAdresse_emp(txtAddrssE.getText());
            e.setTel(txtTelE.getText());
            e.setFonction(cbxFonction.getSelectedItem().toString());

            Connection conn = MyUtil.seConnecter();
            PreparedStatement ps = conn.prepareStatement("update employer set nom_emp=?,prenom_emp=?,adresse_emp=?,tel_emp=?,fonction=? where cin_emp=?");
            ps.setString(1, e.getNom_emp());
            ps.setString(2, e.getPrenom_emp());
            ps.setString(3, e.getAdresse_emp());
            ps.setString(4, e.getTel());
            ps.setString(5, e.getFonction());
            ps.setString(6, e.getCin_emp());
            ps.executeUpdate();
            ps.close();
            conn.close();

            df.setValueAt(e.getCin_emp(), pos, 0);
            df.setValueAt(e.getNom_emp(), pos, 1);
            df.setValueAt(e.getPrenom_emp(), pos, 2);
            df.setValueAt(e.getAdresse_emp(), pos, 3);
            df.setValueAt(e.getTel(), pos, 4);
            df.setValueAt(e.getFonction(), pos, 5);

            JOptionPane.showMessageDialog(null, "employer modifié avec succes.");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "erreur "+ex.getMessage());
        }
    }//GEN-LAST:event_btnModActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        // TODO add your handling code here:
        txtCinE.setText("");
        txtNomE.setText("");
        txtPrnmE.setText("");
        txtAddrssE.setText("");
        txtTelE.setText("");
        cbxFonction.setSelectedItem(null);
    }//GEN-LAST:event_btnNewActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            int id = 0;
            String cin = txtCINRech.getText();
            Connection conn = MyUtil.seConnecter();
            PreparedStatement ps = conn.prepareStatement("select cin_emp,nom_emp,prenom_emp,adresse_emp,tel_emp,fonction from employer where cin_emp = '" + cin + "'");
            ResultSet rs = ps.executeQuery();
            while(rs.next()) {
                id = 1;
                txtCinE.setText(rs.getString(1));
                txtNomE.setText(rs.getString(2));
                txtPrnmE.setText(rs.getString(3));
                txtAddrssE.setText(rs.getString(4));
                txtTelE.setText(rs.getString(5));
                cbxFonction.setSelectedItem(rs.getString(6));
            }
            if(id == 0) {
                JOptionPane.showMessageDialog(null, "CIN Introuvable !");
                txtCinE.setText(null);
                txtNomE.setText(null);
                txtPrnmE.setText(null);
                txtAddrssE.setText(null);
                txtTelE.setText(null);
                cbxFonction.setSelectedItem(null);
            }
        } catch (Exception ex) {
            Logger.getLogger(EmployeesFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjout;
    private javax.swing.JButton btnDernier;
    private javax.swing.JButton btnMod;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnPreced;
    private javax.swing.JButton btnPremier;
    private javax.swing.JButton btnSuiv;
    private javax.swing.JButton btnSupp;
    private javax.swing.JComboBox<String> cbxFonction;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtAddrssE;
    private javax.swing.JTextField txtCINRech;
    private javax.swing.JTextField txtCinE;
    private javax.swing.JTextField txtNomE;
    private javax.swing.JTextField txtPrnmE;
    private javax.swing.JTextField txtTelE;
    // End of variables declaration//GEN-END:variables

    private void afficher() {
        if(le.size() > 0) {
            Employer e = le.get(pos);
            txtCinE.setText(e.getCin_emp());
            txtNomE.setText(e.getNom_emp());
            txtPrnmE.setText(e.getPrenom_emp());
            txtAddrssE.setText(e.getAdresse_emp());
            txtTelE.setText(e.getTel());
            cbxFonction.setSelectedItem(e.getFonction());
        }
    }
}
