/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg.views;
import java.awt.TextField;
import java.sql.Connection;


import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pkg.dao.MyUtil;
import pkg.models.Reparation;
import pkg.models.Voiture;


/**
 *
 * @author user
 */
public class ReparationFrame extends javax.swing.JInternalFrame {
    ArrayList<Reparation> lr = new ArrayList<>();
    ArrayList<Voiture> lv = new ArrayList<>();
    int pos = 0;
    DefaultTableModel df = null;
            

    /**
     * Creates new form ReparationFrame
     */
    public ReparationFrame() {
        initComponents();
        df = (DefaultTableModel) jTable1.getModel();
        df.setRowCount(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNoRep = new javax.swing.JTextField();
        txtMontant = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDesc = new javax.swing.JTextPane();
        jLabel5 = new javax.swing.JLabel();
        txtMat = new javax.swing.JTextField();
        btnRechercheNoRep = new javax.swing.JButton();
        cbxVoiture = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        dChooser = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        btnAjouter = new javax.swing.JButton();
        btnSupprimer = new javax.swing.JButton();
        btnModifier = new javax.swing.JButton();
        Nouveau = new javax.swing.JButton();
        btnPremier = new javax.swing.JButton();
        btnPreced = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnDernier = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtRechNo = new javax.swing.JTextField();
        btnRechNoRep = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 14))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel1.setText("No Rep : ");

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel3.setText("Montant : ");

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel4.setText("Description :");

        txtNoRep.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        txtMontant.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        txtDesc.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jScrollPane1.setViewportView(txtDesc);

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel5.setText("Matricule Voiture : ");

        txtMat.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtMat.setEnabled(false);

        btnRechercheNoRep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkg/imgs/search_30px.png"))); // NOI18N
        btnRechercheNoRep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRechercheNoRepActionPerformed(evt);
            }
        });

        cbxVoiture.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        cbxVoiture.setToolTipText("Selectionner une voiture");
        cbxVoiture.setName(""); // NOI18N
        cbxVoiture.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxVoitureItemStateChanged(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel6.setText("Date de Rep : ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNoRep, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMontant, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1)))
                .addGap(18, 18, 18)
                .addComponent(btnRechercheNoRep)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cbxVoiture, 0, 162, Short.MAX_VALUE)
                        .addComponent(txtMat))
                    .addComponent(dChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cbxVoiture, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMat, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                            .addComponent(dChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 37, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtNoRep, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnRechercheNoRep))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMontant, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gerer Rep", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 14))); // NOI18N

        btnAjouter.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnAjouter.setText("Ajouter");
        btnAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterActionPerformed(evt);
            }
        });

        btnSupprimer.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnSupprimer.setText("Supprimer");
        btnSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupprimerActionPerformed(evt);
            }
        });

        btnModifier.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnModifier.setText("Modifier");
        btnModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifierActionPerformed(evt);
            }
        });

        Nouveau.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        Nouveau.setText("Nouveau");
        Nouveau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NouveauActionPerformed(evt);
            }
        });

        btnPremier.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnPremier.setText("|<");
        btnPremier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPremierActionPerformed(evt);
            }
        });

        btnPreced.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnPreced.setText("<<");
        btnPreced.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrecedActionPerformed(evt);
            }
        });

        btnNext.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnNext.setText(">>");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnDernier.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnDernier.setText(">|");
        btnDernier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDernierActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(93, Short.MAX_VALUE)
                .addComponent(btnAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnSupprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnModifier, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnPremier)
                        .addGap(18, 18, 18)
                        .addComponent(btnPreced)
                        .addGap(18, 18, 18)
                        .addComponent(btnNext)
                        .addGap(18, 18, 18)
                        .addComponent(btnDernier)))
                .addGap(47, 47, 47)
                .addComponent(Nouveau, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSupprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModifier, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nouveau, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPremier)
                    .addComponent(btnPreced)
                    .addComponent(btnNext)
                    .addComponent(btnDernier))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Liste Rep", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 14))); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No Rep", "Description", "Montant", "Matricule", "Date Rep"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel2.setText("Rechercher par No de Reparation : ");

        txtRechNo.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        btnRechNoRep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkg/imgs/search_30px.png"))); // NOI18N
        btnRechNoRep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRechNoRepActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtRechNo, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRechNoRep, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRechNoRep, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtRechNo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        try {
            // TODO add your handling code here:
            Connection con=MyUtil.seConnecter();
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("select * from voiture");
            while(rs.next()){
                cbxVoiture.addItem(new Voiture(rs.getString(1),rs.getInt(2), rs.getString(3), rs.getString(4),
                        rs.getString(5), rs.getString(6), rs.getFloat(7))); //combobox 
            }
             rs.close();
            ResultSet ra=st.executeQuery("select numrep,dscrp,montant,matricule,daterep from reparation join voiture using(matricule) order by numrep");
            while(ra.next()){
                lr.add (new Reparation(ra.getInt("numrep"), 
                         ra.getString("dscrp"), ra.getFloat("montant"), ra.getString("matricule"), ra.getDate("daterep")));
                
            }
            ra.close();
            afficher();
            ResultSet re = st.executeQuery("select numrep,dscrp,montant,matricule,daterep from reparation join voiture using(matricule) order by numrep");
            while(re.next()) {
                df.addRow(new Object[] {re.getString("numrep"),re.getString("dscrp"),re.getFloat("montant"),re.getString("matricule"),re.getDate("daterep")});
            }
            re.close();
        } catch (Exception ex) {
            Logger.getLogger(ReparationFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_formInternalFrameOpened

    private void btnAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterActionPerformed
        try {
            // TODO add your handling code here:
            Reparation r = new Reparation();
            Voiture v = (Voiture) cbxVoiture.getSelectedItem();
            r.setDscrp(txtDesc.getText());
            r.setMontant(Float.parseFloat(txtMontant.getText()));
            SimpleDateFormat sdf = new SimpleDateFormat("dd-MMM-yyyy");
            String date = sdf.format(dChooser.getDate());
            
            Connection con = MyUtil.seConnecter();
            PreparedStatement ps = con.prepareStatement("insert into reparation values(seq_rep.NEXTVAL,?,?,?,?)",new int[]{1});
            
            //ps.setString(1, norep);
            ps.setString(1, r.getDscrp());
            ps.setFloat(2, r.getMontant());
            ps.setString(3, v.getMatricule());
            ps.setString(4, date);
            ps.executeUpdate();
            ResultSet rs = ps.getGeneratedKeys();
            rs.next();
            Reparation rr = new Reparation(rs.getInt(1),r.getDscrp(),r.getMontant(),r.getMatricule(),dChooser.getDate());
            ps.close();
            con.close();
            lr.add(r);
            df.addRow(new Object[] {rr.getNumrep(),rr.getDscrp(),rr.getMontant(),v.getMatricule(),sdf.format(dChooser.getDate())});
            
            JOptionPane.showMessageDialog(null, "Reparation Enregistré Avec Succes !");
            
            
        } catch (ParseException ex) {
            Logger.getLogger(ReparationFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Remplire Tous les Champs");
        }
    }//GEN-LAST:event_btnAjouterActionPerformed

    private void btnPremierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPremierActionPerformed
        // TODO add your handling code here:
          try{
            pos=0;
            afficher();
        }catch(IndexOutOfBoundsException e){
            JOptionPane.showMessageDialog(null, "Liste des Reparations est vide");
        }
    }//GEN-LAST:event_btnPremierActionPerformed

    private void btnPrecedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrecedActionPerformed
        // TODO add your handling code here:
         try{
            pos--;
            afficher();
        }catch(IndexOutOfBoundsException e){
            pos++;
        }
    }//GEN-LAST:event_btnPrecedActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        try{
            pos++;
            afficher();
        }catch(IndexOutOfBoundsException e){
            pos--;
        }
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnDernierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDernierActionPerformed
        // TODO add your handling code here:
        try{
            pos=lr.size()-1;
            afficher();
        }catch(IndexOutOfBoundsException e){
            JOptionPane.showMessageDialog(null, "Liste des Reparations est vide");
        }
    }//GEN-LAST:event_btnDernierActionPerformed

    private void btnModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierActionPerformed
        try {
            // TODO add your handling code here:
            Reparation r = lr.get(pos);
            //Voiture v = (Voiture) cbxVoiture.getSelectedItem();
            r.setNumrep(Integer.parseInt(txtNoRep.getText()));
            r.setDscrp(txtDesc.getText());
            r.setMontant(Float.parseFloat(txtMontant.getText()));
            r.setMatricule(txtMat.getText());
            SimpleDateFormat sdf = new SimpleDateFormat("dd-MMM-yyyy");
            String date = sdf.format(dChooser.getDate());
            lr.add(r);
            
            Connection con = MyUtil.seConnecter();
            PreparedStatement ps = con.prepareStatement("update reparation set dscrp = ?,montant = ?,matricule = ?,daterep = ? where numrep = ?");
            
            ps.setString(1, r.getDscrp());
            ps.setFloat(2, r.getMontant());
            ps.setString(3, r.getMatricule());
            ps.setString(4, date);
            ps.setInt(5, r.getNumrep());
            ps.executeUpdate();
            ps.close();
            con.close();
            
            df.setValueAt(r.getNumrep(), pos, 0);
            df.setValueAt(r.getDscrp(), pos, 1);
            df.setValueAt(r.getMontant(), pos, 2);
            df.setValueAt(r.getMatricule(), pos, 3);
            df.setValueAt(r.getDate(), pos, 4);
            
            JOptionPane.showMessageDialog(null, "Modifié Avec Succes");
        } catch (Exception ex) {
            Logger.getLogger(ReparationFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnModifierActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
          int l=jTable1.getSelectedRow();
        if(l>=0)
        {
            pos=l;
            afficher();
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnRechercheNoRepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRechercheNoRepActionPerformed
        // TODO add your handling code here:
        Reparation r = new Reparation();
        int norep = 0;
        String txtnorep = txtNoRep.getText();

        try {
            Connection conn = MyUtil.seConnecter();
            PreparedStatement ps = conn.prepareStatement("select matricule,montant,dscrp,daterep from reparation join voiture using(matricule) where numrep = '"+txtnorep+"'");
            ResultSet rs = ps.executeQuery();
            while(rs.next()) {
                norep = 1;
                cbxVoiture.setSelectedItem(null);
                txtMat.setText(rs.getString(1));
                txtMontant.setText(rs.getString(2));
                txtDesc.setText(rs.getString(3));
                dChooser.setDate(rs.getDate(4));

            }
            if(norep == 0) {
                JOptionPane.showMessageDialog(null, "Num de Reparation invalide !");
            }
        } catch (Exception ex) {
            Logger.getLogger(ReparationFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRechercheNoRepActionPerformed

    private void btnSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupprimerActionPerformed
        try {
            // TODO add your handling code here:
            Reparation r = lr.get(pos);
            Connection conn = MyUtil.seConnecter();
            PreparedStatement ps = conn.prepareStatement("delete from reparation where numrep = ?");
            ps.setInt(1, r.getNumrep());
            ps.executeUpdate();
            ps.close();
            conn.close();
            
            try{
                lr.remove(r);
                df.removeRow(pos);
                pos--;
                afficher();
            }catch(IndexOutOfBoundsException ex){
                pos++;
                afficher();
            }
            JOptionPane.showMessageDialog(null, "Supprimé avec succes");
        } catch (Exception ex) {
            Logger.getLogger(ReparationFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSupprimerActionPerformed

    private void cbxVoitureItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxVoitureItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxVoitureItemStateChanged

    private void NouveauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NouveauActionPerformed
        // TODO add your handling code here:
        txtNoRep.setEnabled(false);
        txtNoRep.setText("");
        txtMontant.setText("");
        txtDesc.setText("");
        txtMat.setText("");
        cbxVoiture.setSelectedItem(null);
        dChooser.setDate(null);
    }//GEN-LAST:event_NouveauActionPerformed

    private void btnRechNoRepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRechNoRepActionPerformed
        try {
            // TODO add your handling code here:
            int id = 0;
            String idrep = txtRechNo.getText();
            
            Connection conn = MyUtil.seConnecter();
            PreparedStatement ps = conn.prepareStatement("select numrep,dscrp,montant,matricule,daterep from reparation where numrep = '" + idrep + "'");
            ResultSet rs = ps.executeQuery();
            
            while(rs.next()) {
                id = 1;
                txtNoRep.setText(rs.getInt(1)+"");
                txtDesc.setText(rs.getString(2));
                txtMontant.setText(rs.getFloat(3)+"");
                txtMat.setText(rs.getString(4));
                dChooser.setDateFormatString(rs.getDate(5)+"");
            }
        } catch (Exception ex) {
            Logger.getLogger(ReparationFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRechNoRepActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Nouveau;
    private javax.swing.JButton btnAjouter;
    private javax.swing.JButton btnDernier;
    private javax.swing.JButton btnModifier;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPreced;
    private javax.swing.JButton btnPremier;
    private javax.swing.JButton btnRechNoRep;
    private javax.swing.JButton btnRechercheNoRep;
    private javax.swing.JButton btnSupprimer;
    private javax.swing.JComboBox<Voiture> cbxVoiture;
    private com.toedter.calendar.JDateChooser dChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextPane txtDesc;
    private javax.swing.JTextField txtMat;
    private javax.swing.JTextField txtMontant;
    private javax.swing.JTextField txtNoRep;
    private javax.swing.JTextField txtRechNo;
    // End of variables declaration//GEN-END:variables

    private void afficher() {
         if(lr.size()>0){
            Reparation r=lr.get(pos);
            txtNoRep.setText(r.getNumrep()+"");
            txtDesc.setText(r.getDscrp());
            txtMontant.setText(r.getMontant()+"");
            txtMat.setText(r.getMatricule());
            dChooser.setDate(r.getDate());
            cbxVoiture.setSelectedItem(null);
         }
    }
}
